# Generated by Django 6.0.2 on 2026-02-24 04:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Isletme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('bolge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bolge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Kurye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(max_length=20)),
                ('bolgeler', models.ManyToManyField(to='core.bolge')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fis_no', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('adres', models.CharField(max_length=255)),
                ('odeme_tipi', models.CharField(choices=[('nakit', 'Nakit'), ('online', 'Online'), ('kart', 'Kart'), ('metropol', 'Metropol')], max_length=20)),
                ('fis_foto', models.ImageField(upload_to='fisler/')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('alindi', 'Alındı'), ('teslim', 'Teslim Edildi')], default='bekliyor', max_length=20)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('alan_kurye', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.kurye')),
                ('isletme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.isletme')),
                ('teslim_bolge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bolge')),
            ],
        ),
    ]
